### ISSUE TITLE
Issue with Third Party RPM's installation SSC VM's

### ISSUE THREAD

**Issue by shailesh-vaidya** [Seagate/cortx-re#416]
Recently @gauravchaudhari02 reported that he is facing [package installation issue](https://jts.seagate.com/browse/EOS-18072?focusedCommentId=2090820&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2090820) while OVA creation. Issue is due to unavailability of python36-packaging package. Thanks to @gowthamchinna  We added required packages and unblocked deployment. However I see couple of process issues in this.

Issue was only observed for @gauravchaudhari02 and @hessio  and NOT on SSC VM’s. This is because on SSC VM default EPEL repo named - **EOS_EPEL-7_EPEL-7** pointing to https://ssc-satellite1.colo.seagate.com/pulp/repos/EOS/Production/CentOS-7/custom/EPEL-7/EPEL-7 .  Hence even though package is not available in 3rd party it gets installed from above location. I feel we should disable this default repo to catch such error’s on SSC VM’s infra.

**Comment by hessio** [comment]
Hi @shailesh-vaidya @gauravchaudhari02 what is the status of this issue? Is the work for this ticket scheduled to be done or is it still in a backlog?

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-28334. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by shailesh-vaidya** [comment]
@mukul-seagate11 Could you please create a Jira ticket for the same to track this issue.

**Comment by mukul-seagate11** [comment]
@shailesh-vaidya, Its already created & being synced via BG i.e. https://jts.seagate.com/browse/CORTX-28334

**Comment by cortx-admin** [comment]
> Amit Kapil commented in Jira Server:

[~729494] and [~934370] Please review and update.

**Comment by cortx-admin** [comment]
> Shailesh Vaidya commented in Jira Server:

This issue is observed in old non K8s based deployment where internal SSC VM's has default EPEL repository configured and we have to install an epel-release package as part of the deployment process for the community (outside Seagate n/w). This leads to a scenario where deployment works fine internally but fails for the community. 

This is obsolete with K8s-based deployment as
 * We are providing cortx-all image with all the required packages pre-installed. 
 * Steps to generate cortx-all image outside Seagate are optimized for outside Seagate network.

**Comment by cortx-admin** [comment]
> Shailesh Vaidya commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Shailesh Vaidya commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Shailesh Vaidya commented in Jira Server:

.
