### ISSUE TITLE
Align python-requirements files naming to standard conventions. 

### ISSUE THREAD

**Issue by shailesh-vaidya** [Seagate/cortx-re#476]
@ujjwalpl suggested at - https://github.com/Seagate/cortx-re/pull/472#pullrequestreview-689134304
Suggestion: The file name needs to change align with the conventions used across

python-requirements.txt for direct dependencies
python-requirements.ext.txt for indirect dependencies

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-28335. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by hessio** [comment]
Hi @shailesh-vaidya is this issue fixed since PR [#472](https://github.com/Seagate/cortx-re/pull/472) was merged?

**Comment by shailesh-vaidya** [comment]
Closing issue as an obsolete
