### ISSUE TITLE
BG test

### ISSUE THREAD

**Issue by venkuppu-chn** [Seagate/cortx-re#861]
BG test

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-28864. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Venkatesh K commented in Jira Server:

Test ticket. Simply close it.

**Comment by cortx-admin** [comment]
> Venkatesh K commented in Jira Server:

BG test ticket.

**Comment by cortx-admin** [comment]
> Venkatesh K commented in Jira Server:

Verified
